from lib.estimate_reading_time import *

def test_estimate_reading_time_less_than_200_words():
    result = estimate_reading_time("Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day")
    assert result == "Estimated reading time: less than 1 minute"

def test_estimate_reading_time_200_words():
    result = estimate_reading_time("Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day")
    assert result == "Estimated reading time: 1 minute"

def test_estimate_reading_time_400_words():
    result = estimate_reading_time("Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day")
    assert result == "Estimated reading time: 2 minutes"

def test_estimate_reading_time_300_words():
    result = estimate_reading_time("Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day Hello world how are you doing on this fine day")
    assert result == "Estimated reading time: 2 minutes"

def test_estimate_reading_time_no_words():
    result = estimate_reading_time("")
    assert result == "Cannnot estimate reading time"
